Created Readme.md
SohamRatnaparkhi/DSA-Course pull request #2
Opened 2022-10-01 19:32 UTC by Viki-07

Added a readme file in which I added Binary Tree DSA links.

2022-10-01 19:34 UTC, Viki-07 commented
@SohamRatnaparkhi

2022-10-01 20:30 UTC, SohamRatnaparkhi requested changes
Current format wont work. I have requested changes and explained the format in current issue's comment.

2022-10-01 20:30 UTC, SohamRatnaparkhi commented on Readme.md
> +Binary Tree
``` markdown
<details>
  <summary>Binary Tree</summary>
  <a href="https://github.com/Viki-07/DSA-Course/blob/master/BinaryTree/BinaryTreeNode.java" >Binary Tree Node class</a> <br>
 <a href="https://github.com/Viki-07/DSA-Course/blob/master/BinaryTree/BInaryTreeLength.java" >Length of tree </a>
</details>
```

2022-10-01 20:30 UTC, SohamRatnaparkhi commented
Also adding few more links will be good!

2022-10-04 05:11 UTC, Viki-07 reviewed
Reviewed and updated format

2022-10-04 05:12 UTC, Viki-07 commented
@SohamRatnaparkhi

2022-10-04 06:17 UTC, SohamRatnaparkhi commented
Looks good to me! Will merge it.
Thankyou for contributing!

2022-10-04 06:17 UTC, merged

2022-10-04 06:24 UTC, SohamRatnaparkhi commented
You created your own  README.md file but you have to make changes in already present README.md file.
You code is perfect but you need to add it after the hashmaps part in README.md file
And make a new pull request.